# Generated by Django 4.2 on 2023-04-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("curso", models.CharField(max_length=100)),
                ("numero_cursada", models.IntegerField(max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name="Estudiantes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("dni", models.IntegerField(max_length=999999999)),
                ("edad", models.IntegerField(max_length=120)),
                ("email", models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Profesores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("dni", models.IntegerField(max_length=999999999)),
                ("email", models.EmailField(max_length=100)),
                ("profesion", models.CharField(max_length=100)),
            ],
        ),
    ]
