# Generated by Django 4.2 on 2023-04-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App_1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="numero_cursada",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="estudiantes",
            name="dni",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="estudiantes",
            name="edad",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="profesores",
            name="dni",
            field=models.IntegerField(),
        ),
    ]
