# Generated by Django 4.2 on 2023-04-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App_1", "0002_alter_curso_numero_cursada_alter_estudiantes_dni_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="numero_cursada",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="estudiantes",
            name="dni",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="estudiantes",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="profesores",
            name="dni",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="profesores",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
