# Generated by Django 4.2 on 2023-04-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App_1", "0004_curso_docente"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="alumnos",
            field=models.ManyToManyField(to="App_1.estudiantes"),
        ),
    ]
